# Generated by Django 6.0.1 on 2026-01-21 06:44

from django.db import migrations
from django.db import migrations, models
import uuid
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
