# Generated by Django 6.0.1 on 2026-01-21 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
