# Generated by Django 6.0.1 on 2026-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='media/project1.png', upload_to='media/'),
        ),
    ]
